# Generated by Django 4.2.15 on 2024-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sections",
            name="description",
            field=models.TextField(blank=True, max_length=700, null=True),
        ),
    ]
