# Generated by Django 4.2.15 on 2024-08-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sections_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.PositiveIntegerField()),
                ("phone", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ذكر"), ("female", "أنثى")], max_length=6
                    ),
                ),
                ("symptoms", models.TextField()),
            ],
        ),
    ]
